trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'your-acr-service-connection'
    repository: 'backend'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest
